# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: whiteboard-deployment
  namespace: default
spec:
  replicas: 1 # tells deployment to run 1 pods matching the template
  selector:
    matchLabels:
      run: whiteboard
  template:
    metadata:
      labels:
        run: whiteboard
    spec:
      containers:
      - image: registry.ng.bluemix.net/quan_thinklabs/whiteboard
        name: whiteboard
        ports:
        - containerPort: 9002
