apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-10-13T04:53:03Z
  labels:
    run: whiteboard-deployment
  name: whiteboard-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30217
    port: 9002
    protocol: TCP
    targetPort: 9002
  selector:
    run: whiteboard
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
